## The saved data of a player.

class_name PlayerSavedData extends Resource

## A random GUID generated by the client, used to differentiate players.
@export var id: String

## The skin the player was using.
@export var skin: PlayerSkin
